language: php

php: 
  - 5.3
  - 5.4

before_script:
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar update

script: phpunit --coverage-text --configuration phpunit.travis.xml

notifications:
  email: false
