language: php

php: 
  - 5.3.3
  - 5.3
  - 5.4

before_script:
  - composer install --dev

script: phpunit --coverage-text --configuration phpunit.travis.xml

notifications:
  email: false
  hipchat: b00ece55a12a4a46874554f64029c9@Allgemein
