language: php

php: 
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

before_install:
  - composer self-update

install:
  - composer install --dev --prefer-source

script:
  - phpunit --coverage-text --configuration phpunit.travis.xml

notifications:
  email: false
  hipchat: b00ece55a12a4a46874554f64029c9@Allgemein
